#pragma once
#include <windows.h>
#include <iostream>
#include <cstdint>
#include <memory>
#include <vector>
#include <thread>
#include <chrono>
#include <array>
#include <fstream>
#include <istream>
#include <unordered_map>
#include <intrin.h>
#include "menu/imgui/imgui.h"
#include "menu/imgui/impl/imgui_impl_dx9.h"
#include "menu/imgui/impl/imgui_impl_win32.h"
#include "sdk/interfaces/interfaces.hpp"
#include "sdk/sdk.hpp"
#include "utilities/render/render.hpp"
#include "utilities/globals/globals.hpp"
#include "utilities/utilities.hpp"
#include "utilities/math/math.hpp"
#include "menu/vars/vars.hpp"
#include "features/features.hpp"